# Generated by Django 3.2.19 on 2024-04-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.CharField(db_index=True, max_length=100)),
                ('examinador_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('examinador_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('examinador_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('examinador_4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('examinador_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pesos')),
            ],
        ),
    ]
