# Generated by Django 3.2.19 on 2024-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='numProva',
            new_name='prova',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='aprovado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilitado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='idTipo',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
