# Generated by Django 3.2.19 on 2024-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240329_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='idTipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
