# Generated by Django 3.2.19 on 2024-03-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tipo_idtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='numTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo', to='main.tipo'),
        ),
    ]
