# Generated by Django 3.2.19 on 2024-04-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_concurso_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='aprovado',
        ),
    ]
