# Generated by Django 3.2.19 on 2024-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_candidato_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='precedencia',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
